# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Check

on: push

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installing dependencies
        run: |
          sudo yarn global add newman wait-on
          echo "$(yarn global bin)" >> $GITHUB_PATH

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set datetime
        run: |
          sudo timedatectl set-ntp 0
          sudo date --set "2 dec 2020"

      - name: Compile
        run: mvn clean compile

      - name: Test
        run: mvn test

      - name: Start app
        run: mvn exec:java &
        env:
          SPAMDUL_API_MODE: test

      - name: API test
        run: |
          wait-on http://localhost:8080/api/ping
          newman run SPAMD-UL.postman_collection.json
